version: '3.8'

services:
  database:
    container_name: mystic-matches-postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env.local
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  # api:
  #   container_name: mystic-matches-api
  #   restart: always
  #   build:
  #     context: .
  #   ports:
  #     - '3001:3001'
  #   depends_on:
  #     - database
  #   env_file:
  #     - .env.local
  pgadmin:
    container_name: mystic-matches-pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env.local
    ports:
      - '5050:80'
volumes:
  postgres-data: